//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPA.BOL
{
    using System;
    
    public partial class Adresse
    {
        public string ComplementIdentification { get; set; }
        public string NumeroNomVoie { get; set; }
        public string ComplementAdresse { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }
    }
}
