//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPA.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pee()
        {
            this.PeriodesPee = new HashSet<Periode_Pee>();
        }
    
        public int IdPee { get; set; }
        public int IdStagiaire { get; set; }
        public int IdTuteur { get; set; }
        public int IdResponsableJuridique { get; set; }
        public int IdEntreprise { get; set; }
        public int IdOffreFormation { get; set; }
    
        public virtual Entreprise Entreprise { get; set; }
        public virtual Personne ResponsableJuridique { get; set; }
        public virtual Stagiaire Stagiaire { get; set; }
        public virtual Personne Tuteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Periode_Pee> PeriodesPee { get; set; }
    }
}
