//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPA.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periode_Pee
    {
        public int IdPee { get; set; }
        public System.DateTime DateDebutPeriodePee { get; set; }
        public System.DateTime DateFinPeriodePee { get; set; }
    
        public virtual Pee Pee { get; set; }
    }
}
