//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPA.BOL {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Annotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Annotations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AFPA.BOL.Annotations", typeof(Annotations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code Postal.
        /// </summary>
        public static string Adresse_CodePostal_Name {
            get {
                return ResourceManager.GetString("Adresse_CodePostal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complément Adresse.
        /// </summary>
        public static string Adresse_ComplementAdresse_Name {
            get {
                return ResourceManager.GetString("Adresse_ComplementAdresse_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complément.
        /// </summary>
        public static string Adresse_ComplementIdentification_Name {
            get {
                return ResourceManager.GetString("Adresse_ComplementIdentification_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro et Voie.
        /// </summary>
        public static string Adresse_NumeroNomVoie_Name {
            get {
                return ResourceManager.GetString("Adresse_NumeroNomVoie_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        public static string Adresse_Ville_Name {
            get {
                return ResourceManager.GetString("Adresse_Ville_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code postal doit comporter 5 chiffres.
        /// </summary>
        public static string CodePostal_FR {
            get {
                return ResourceManager.GetString("CodePostal_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SIRET.
        /// </summary>
        public static string Entreprise_NumeroSIRET_Description {
            get {
                return ResourceManager.GetString("Entreprise_NumeroSIRET_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SIRET.
        /// </summary>
        public static string Entreprise_NumeroSIRET_Name {
            get {
                return ResourceManager.GetString("Entreprise_NumeroSIRET_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SIRET.
        /// </summary>
        public static string Entreprise_NumeroSIRET_ShortName {
            get {
                return ResourceManager.GetString("Entreprise_NumeroSIRET_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raison sociale.
        /// </summary>
        public static string Entreprise_RaisonSociale_Description {
            get {
                return ResourceManager.GetString("Entreprise_RaisonSociale_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raison sociale.
        /// </summary>
        public static string Entreprise_RaisonSociale_Name {
            get {
                return ResourceManager.GetString("Entreprise_RaisonSociale_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raison sociale.
        /// </summary>
        public static string Entreprise_RaisonSociale_ShortName {
            get {
                return ResourceManager.GetString("Entreprise_RaisonSociale_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;établissement de formation.
        /// </summary>
        public static string Etablissement_Designation_Description {
            get {
                return ResourceManager.GetString("Etablissement_Designation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le {0} doit commencer par un caractère en majuscule suivis de minuscules !.
        /// </summary>
        public static string Etablissement_Designation_Format {
            get {
                return ResourceManager.GetString("Etablissement_Designation_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;établissement.
        /// </summary>
        public static string Etablissement_Designation_Name {
            get {
                return ResourceManager.GetString("Etablissement_Designation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom établissement.
        /// </summary>
        public static string Etablissement_Designation_ShortName {
            get {
                return ResourceManager.GetString("Etablissement_Designation_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant Etablissement.
        /// </summary>
        public static string Etablissement_IdEtablissement_Description {
            get {
                return ResourceManager.GetString("Etablissement_IdEtablissement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant.
        /// </summary>
        public static string Etablissement_IdEtablissement_Name {
            get {
                return ResourceManager.GetString("Etablissement_IdEtablissement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le {0} doit comporter 5 chiffres..
        /// </summary>
        public static string Etablissement_IdEtablissement_Valeur {
            get {
                return ResourceManager.GetString("Etablissement_IdEtablissement_Valeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de communiquer l&apos;information {0}..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;information {0} doit comporter au moins {2} caractères et au plus {1}.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
    }
}
