//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPA.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etablissement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etablissement()
        {
            this.OffresFormation = new HashSet<OffreFormation>();
            this.EtablissementsRattaches = new HashSet<Etablissement>();
            this.Adresse = new Adresse();
        }
    
        public string IdEtablissement { get; set; }
        public string DesignationEtablissement { get; set; }
        public string IdEtablissementRattachement { get; set; }
    
        public Adresse Adresse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffreFormation> OffresFormation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etablissement> EtablissementsRattaches { get; set; }
        public virtual Etablissement EtablissementRattachement { get; set; }
    }
}
