//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPA.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffreFormation
    {
        public OffreFormation()
        {
            this.StagiairesOffreFormation = new HashSet<Stagiaire_OffreFormation>();
        }
    
        public int IdOffreFormation { get; set; }
        public string IdEtablissement { get; set; }
        public System.DateTime DateDebutOffreFormation { get; set; }
        public System.DateTime DateFinOffreFormation { get; set; }
        public Nullable<int> IdPersonne { get; set; }
        public string IdProduitFormation { get; set; }
    
        public virtual Etablissement Etablissement { get; set; }
        public virtual ProduitDeFormation ProduitDeFormation { get; set; }
        public virtual ICollection<Stagiaire_OffreFormation> StagiairesOffreFormation { get; set; }
        public virtual CollaborateurAfpa FormateurReferent { get; set; }
    }
}
