//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPA.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagiaire_OffreFormation
    {
        public int IdPersonne { get; set; }
        public int IdOffreFormation { get; set; }
        public string IdEtablissement { get; set; }
        public System.DateTime DateEntreeStagiaire { get; set; }
        public Nullable<System.DateTime> DateSortieStagiaire { get; set; }
    
        public virtual Stagiaire Stagiaire { get; set; }
        public virtual OffreFormation OffreFormation { get; set; }
    }
}
