//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using AFPA.BOL;
    
    public partial class AFPA_ORMEntities : DbContext
    {
        public AFPA_ORMEntities()
            : base("name=AFPA_ORMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entreprise> Entreprise { get; set; }
        public virtual DbSet<Etablissement> Etablissement { get; set; }
        public virtual DbSet<OffreFormation> OffreFormation { get; set; }
        public virtual DbSet<Pee> Pee { get; set; }
        public virtual DbSet<Periode_Pee> Periode_Pee { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<ProduitDeFormation> ProduitDeFormation { get; set; }
        public virtual DbSet<Stagiaire_OffreFormation> Stagiaire_OffreFormation { get; set; }
    }
}
